// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ProyectoProgramacion.Migrations
{
    [DbContext(typeof(ProyectoP1Context))]
    [Migration("20241105004944_tabla_tipos")]
    partial class tabla_tipos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoProgramacion.Models.Membresias", b =>
                {
                    b.Property<int>("IDcliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IDcliente"));

                    b.Property<int>("TiposMembresia")
                        .HasColumnType("int");

                    b.Property<DateTime>("caducidad")
                        .HasColumnType("datetime2");

                    b.Property<string>("cedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("membresiaID_Membresia")
                        .HasColumnType("int");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDcliente");

                    b.HasIndex("membresiaID_Membresia");

                    b.ToTable("Membresias");
                });

            modelBuilder.Entity("ProyectoProgramacion.Models.TiposMembresia", b =>
                {
                    b.Property<int>("ID_Membresia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Membresia"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Membresia");

                    b.ToTable("TiposMembresia");
                });

            modelBuilder.Entity("ProyectoProgramacion.Models.Usuarios", b =>
                {
                    b.Property<int>("ID_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_usuario"));

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_usuario");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("ProyectoProgramacion.Models.Membresias", b =>
                {
                    b.HasOne("ProyectoProgramacion.Models.TiposMembresia", "membresia")
                        .WithMany()
                        .HasForeignKey("membresiaID_Membresia");

                    b.Navigation("membresia");
                });
#pragma warning restore 612, 618
        }
    }
}
